spring.application.name=api

# URL de conexao com o Neon (PostgreSQL na nuvem)
spring.datasource.url=${DB_URL}

# Credenciais do banco
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura o Hibernate para criar ou atualizar as tabelas do banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=optional:file:.env[.properties]