spring.application.name=api

# URL de conexao (O comando createDatabaseIfNotExist ja cria o banco bibliotech_db sozinho)
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotech_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# Credenciais do seu MySQL (Altere a senha para a sua!)
spring.datasource.username=root
spring.datasource.password=

# Configura o Hibernate para criar ou atualizar as tabelas do banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=optional:file:.env[.properties]