spring.application.name=api
server.port=8081

# URL de conexao com o MariaDB rodando local no Termux
spring.datasource.url=jdbc:mariadb://localhost:3306/bibliotech_db

# Credenciais do banco (ajustado para configuração básica Termux)
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configura o Hibernate para criar ou atualizar as tabelas do banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.config.import=optional:file:.env[.properties]